apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: savelife
type: Opaque
stringData:
  auth-db-url: "jdbc:postgresql://auth-db:5432/authdb"
  auth-db-username: "authuser"
  auth-db-password: "authpass"
  patient-db-url: "jdbc:postgresql://patient-db:5432/patientdb"
  patient-db-username: "patientuser"
  patient-db-password: "patientpass"

